---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  sampleApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Sample Application
  sampleApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Application Version
      SourceBundle:
        S3Bucket: bookapplication01-12-2021
        S3Key: OhioBookProject.war
  sampleConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Configuration Template
      OptionSettings:
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: vpc-0bc15fa494cb899cb
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value:
          Fn::Join:
          - ","
          - - subnet-091abcd0f969db733
            - subnet-0ce84d0c02728d64b
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value:
          Fn::Join:
          - ","
          - - subnet-08c98039caca94fbf
            - subnet-00638a7421bd98c35
      - Namespace: aws:autoscaling:asg
        OptionName: Cooldown
        Value: '180'
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '4'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateEnabled
        Value: true

      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateType
        Value: Health

      - Namespace: aws:autoscaling:trigger
        OptionName: MeasureName
        Value: RequestCount

      - Namespace: aws:autoscaling:trigger
        OptionName: Statistic
        Value: Sum

      - Namespace: aws:autoscaling:trigger
        OptionName: Unit
        Value: Count

      - Namespace: aws:autoscaling:trigger
        OptionName: Period
        Value: 1
      - Namespace: aws:autoscaling:trigger
        OptionName: BreachDuration
        Value: 1

      - Namespace: aws:autoscaling:trigger
        OptionName: UpperThreshold
        Value: 8
      - Namespace: aws:autoscaling:trigger
        OptionName: LowerThreshold
        Value: 2
      SolutionStackName: 64bit Amazon Linux 2 v4.2.8 running Tomcat 8.5 Corretto 11
  sampleEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Environment
      TemplateName:
        Ref: sampleConfigurationTemplate
      VersionLabel:
        Ref: sampleApplicationVersion
