
Resources:
  MyS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: "london-bookapplication-02-12-2021"
  MyS3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: "london-rdsbackups-02-12-2021"